Big refactor
borislav-itskov/schnorrkel.js pull request #2
Opened 2023-05-23 01:02 UTC by LorhanSohaky

I really like your project and I plan to use this library in pwn2winctf.

I've made some changes that I believe will improve the developer experience.

## CI
- added workflow to test the project in different Node versions

## Typescript
- added typescript config
- added build in es6 and es5

## Core
- remove deprecated code ( `new Buffer` )

## Interface
- modified the interface to be simpler to handle the Uint8Array
- I tried to keep the core the same way

2023-05-23 05:16 UTC, borislav-itskov commented
Wow! Great work, thank you for your interest in the library. I'm starting review of the PR and I will keep you in touch :)

2023-05-23 06:40 UTC, borislav-itskov requested changes
Hey there! I left a few comments on things I found, can you check them when you have the time?

Also, I saw the contracts have been deleted and a new testing framework proposed. I don't mind the new testing framework but we were using the contracts for testing the validation on chain. I feel we need to make sure validation is working both on and off chain

2023-05-23 06:40 UTC, borislav-itskov commented on src/schnorrkel.ts
> +  static fromJson(json: string): Schnorrkel {
Setting `nonces` outside the library should be forbidden. It is absolutely crucial for them to be kept private or else you expose the private key. This is the simple schnorr equation:
```
s = k + e*d
```
Where `s` is the signature, `k` is the private nonce, `e` is the message (schnorr challenge) and `d` is the private key. Schnorr only works because `k` is kept secret at all times and a random attacker doesn't know `k` and `d`. Therefore, he cannot derive the private key after the user signs. If somehow `k` is exposed, he just needs to run the mathematical equation above and he steals the private key.

2023-05-23 06:40 UTC, borislav-itskov commented on src/schnorrkel.ts
> +          kTwo: nonce.kTwo.toHex(),
This method exposes the private nonces and no one outside the library should be able to retrieve them at all costs. Please check the my first comment for more information

2023-05-23 06:40 UTC, borislav-itskov commented on src/schnorrkel.ts
> +  }
I like this method and although it's static, it shouldn't be in the Schnorrkel class in my opinion. Generating key pairs is a wallet responsibility. Using it directly from core/index.ts is better

2023-05-23 06:40 UTC, borislav-itskov commented on src/core/index.ts
> +export const _generateRandomKeys = () => {
This method is very useful and in my opinion, we could directly have it return the `KeyPair` type. Unless you want to keep them separated.

2023-05-23 15:56 UTC, LorhanSohaky commented on src/schnorrkel.ts
> +  static fromJson(json: string): Schnorrkel {
In my use case I need to export the data to be able to use it in serverless. I intend to keep the values secret, but I need to have control of this.

![musig_1](https://github.com/borislav-itskov/schnorrkel.js/assets/16273730/589d1687-c37c-4ae6-aa1c-c162e0a08942)
![musig_2](https://github.com/borislav-itskov/schnorrkel.js/assets/16273730/aa855c9e-dd73-4cec-a88d-ed440f0c9c44)

2023-05-25 06:59 UTC, borislav-itskov commented on src/schnorrkel.ts
> +  static fromJson(json: string): Schnorrkel {
As far as I understand, you intend to do, for example, a 2/2 multisig where users have a private key in self-custody.
They use the private key to generate their nonces and send them to your database.
Once all nonces have been generated, you give each user back their private nonces alogn with all the public nonces of the participants.
Each of them signs and sends the signature to the back end.
The back end validates the sum and returns an OK message on success.
(correct me if I'm wrong here)

There are some concerns I would raise:
1. The user needs to trust you. If I have a private key, give my nonces to you and sign a message with those nonce, I'm practically giving my private key to you. You just have to run the schnorr equation to retrieve my private key.
2. If you keep the signatures in the database and your database is hacked, all the private keys of the users can be retrieved.

If the private keys are in your custody, it makes sense as the user is required from the beginning to trust you to use your application. At the very least, he will not expose a private key he uses for other operations as you will generate for him one.

---

The goal of this library is to require the minimum amount of trust where no one except the user has access to their private nonces.
Here's one example of such an architecture:
![Screenshot from 2023-05-25 09-16-19](https://github.com/borislav-itskov/schnorrkel.js/assets/5627274/09f71f89-6077-4fbb-a8f8-8b2b59699a19)


1. Each wallet has a private key that doesn't leave the wallet.
2. Each wallet implements the schnorrkel.js library. Therefore, the private nonces don't leave the wallet instance of the schnorrkel.js library.
3. The back end asks the wallets for the public keys, retrieves them and creates the combined public key.
4. The back end asks the wallets for the public nonces and retrieves them
5. The back end asks each wallet for a signature, providing the message, combined public key and all of the public nonces
6. The back end sums the signatures and validates the combined signature.

This way, you have a separation of concerns:
- wallets are responsible for security - keeping private keys and sensitive signing information
- the back end is responsible for requesting data from the wallets, combining and validating it

That being said, I really like your code and wish to use it but I cannot do so with fromJson and other methods that will push the library being used in a different way or expose sensitive data. It's really important to kind of force this separation of concerns. I can take your code, change it a bit, bring back the contracts and afterwards merge it, if you agree.
Otherwise, of course, you are free to fork it and use it as you see fit. :)

2023-05-25 13:34 UTC, thotypous commented on src/schnorrkel.ts
> +  static fromJson(json: string): Schnorrkel {
> They use the private key to generate their nonces and send them to your database.
> Once all nonces have been generated, you give each user back their private nonces alogn with all the public nonces of the participants.

No, sorry if we were not clear.

The client is a party, the backend is another party. Each of them has its own keypair. Private keys never leak from one party to the other.

But please note our application is not related to finance and is not implemented in a blockchain.

The client communicates with the backend using a HTTP-based API, and there is no persistent connection.

The backend may receive a lot of requests from several clients, thus we need to load balance to different servers in the backend.

If we kept a Schnorkell instance in memory for each on-going signature request, we would need a special load balancer which always sends HTTP requests from the same user to the same server. It would also be harder to protect from DoS attacks intending to start several signature requests and never finish them.

However, we do realize the toJson / fromJson functions are utterly dangerous and developers who don't know what they are doing might shot themselves in the foot. We appreciate if you have suggestions to make it explicit the feature is dangerous and requires caution.

But if you still think it is not worth it to maintain this feature, @LorhanSohaky can remove it from the pull request.

2023-05-25 17:11 UTC, borislav-itskov commented on src/schnorrkel.ts
> +  static fromJson(json: string): Schnorrkel {
Okay, guys, thank you sincerely for the feedback. I will need to think a bit more about this one. For the time being, can I ask you for one change?  
I really don't think `generateRandomKeys` should be in the `Schnorrkel` class. The library should not be responsible for generating key pairs. Can we remove it from the class? We can call it from `./core`

2023-05-26 01:03 UTC, LorhanSohaky commented on src/schnorrkel.ts
> +  }
Removed

2023-05-26 13:15 UTC, borislav-itskov commented on src/schnorrkel.ts
> +  static fromJson(json: string): Schnorrkel {
Hey guys,
I talked it over with my colleagues. How about this for a solution:
1. Make another class called `UnsafeSchnorrkel` that extends `Schnorrkel`.
2. Make the `nonces` in the `Schnorrkel` class protected.
3. Move `fromJson` and `toJson` to `UnsafeSchnorrkel`.
4. Initialize and use `UnsafeSchnorrkel`

This makes the most sense for me as I'd like to keep the original implementation intact. I really would like to kind of push the `Schnorrkel` class to be used in a different architecture. But I also don't want to limit its usage as I agree these methods are helpful for your scenario.

If you agree on these changes and make them, we can merge the PR.  
After merging, I will document the `UnsafeSchnorrkel` class, I will bring back the contract tests as I need them and I will make a 2.0.0 version in the npm package.

What do you think?

2023-05-26 22:33 UTC, LorhanSohaky commented on src/schnorrkel.ts
> +  static fromJson(json: string): Schnorrkel {
I modified as suggested

2023-05-29 07:56 UTC, borislav-itskov approved these changes

2023-05-29 08:17 UTC, merged

2023-05-29 08:18 UTC, borislav-itskov commented on src/schnorrkel.ts
> +  static fromJson(json: string): Schnorrkel {
I merged the PR. Thank you for your hard work, guys, the project architecture is 100 times better now! It was a pleasure working with you and I apologize for being a bit sturdy.

2023-05-29 08:22 UTC, borislav-itskov commented
These days, I will write a new readme and publish a 2.0.0 version of the npm package